/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorAutos;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Autos;
import modelo.Marcas;

/**
 *
 * @author LENOVO LEGION 5
 */
public class FrmAutos extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmAutos
     */
    public FrmAutos() {
        initComponents();
        controlAutos.cargar();
        cargarTabla();
    }
    ControladorAutos controlAutos = new ControladorAutos();
    Autos autoSeleccionado = new Autos();
    int pos=-1;
    boolean editar=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textf_chasis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textf_modelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textf_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textf_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_autos = new javax.swing.JTable();
        botn_salir = new javax.swing.JButton();
        boton_guardar = new javax.swing.JButton();
        boton_editar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();
        lblNotifica = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textf_anio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        combob_marca = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Vehículo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 93, 36);

        jLabel2.setText("Chasis:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 50, 30);
        getContentPane().add(textf_chasis);
        textf_chasis.setBounds(50, 60, 140, 30);

        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 60, 50, 30);

        jLabel4.setText("Modelo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 60, 50, 30);
        getContentPane().add(textf_modelo);
        textf_modelo.setBounds(530, 60, 140, 30);

        jLabel5.setText("Color:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 50, 30);
        getContentPane().add(textf_color);
        textf_color.setBounds(50, 140, 140, 30);

        jLabel6.setText("Precio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 150, 50, 30);
        getContentPane().add(textf_precio);
        textf_precio.setBounds(280, 150, 140, 30);

        tabla_autos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Color", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_autos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 670, 260);

        botn_salir.setText("Salir");
        botn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(botn_salir);
        botn_salir.setBounds(600, 220, 80, 30);

        boton_guardar.setText("Guardar");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_guardar);
        boton_guardar.setBounds(20, 220, 80, 30);

        boton_editar.setText("Editar");
        getContentPane().add(boton_editar);
        boton_editar.setBounds(140, 220, 80, 30);

        boton_eliminar.setText("Eliminar");
        getContentPane().add(boton_eliminar);
        boton_eliminar.setBounds(260, 220, 80, 30);
        getContentPane().add(lblNotifica);
        lblNotifica.setBounds(10, 530, 550, 30);

        jLabel7.setText("Año:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 150, 50, 30);
        getContentPane().add(textf_anio);
        textf_anio.setBounds(530, 150, 140, 30);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 530, 100, 30);

        combob_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ferrari", "Mazda", "Toyota", "Chevrolet", "Hyundai" }));
        getContentPane().add(combob_marca);
        combob_marca.setBounds(280, 70, 140, 22);

        setBounds(0, 0, 707, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void botn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_botn_salirActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
        if (textf_chasis.getText().trim().isEmpty()||textf_modelo.getText().trim().isEmpty()||textf_color.getText().trim().isEmpty()||textf_precio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los datos");
        } else {
            try {
                if (editar) {
                    controlAutos.getListaAuto().obtenerDato(pos).setChasis(textf_chasis.getText());
                    controlAutos.getListaAuto().obtenerDato(pos).setMarca(comprobarComboB());
                    controlAutos.getListaAuto().obtenerDato(pos).setModelo(textf_modelo.getText());
                    controlAutos.getListaAuto().obtenerDato(pos).setColor(textf_color.getText());
                    controlAutos.getListaAuto().obtenerDato(pos).setPrecio(Double.parseDouble(textf_precio.getText()));
                    controlAutos.getListaAuto().obtenerDato(pos).setAnio(Integer.parseInt(textf_anio.getText()));
                } else {
                    controlAutos.getListaAuto().insertarAlInicio(new Autos(textf_chasis.getText(), comprobarComboB(), textf_color.getText(),textf_modelo.getText(), Double.valueOf(textf_precio.getText()), Integer.parseInt(textf_anio.getText())));
                }
                controlAutos.guardar();        // TODO add your handling code here:
                cargarTabla();
                
            } catch (IOException ex) {
                System.out.println("no se pudo guardar los datos");
            }
        }
    }//GEN-LAST:event_boton_guardarActionPerformed
    private Marcas comprobarComboB(){
        Marcas m;
        switch (combob_marca.getSelectedIndex()) {
                        case 0:
                            m= Marcas.Ferrari;
                            break;
                        case 1:
                            m= Marcas.Mazda;
                            break;
                        case 2:
                            m= Marcas.Toyota;
                            break;
                        case 3:
                            m= Marcas.Chevrolet;
                            break;
                        case 4:
                            m= Marcas.Hyundai;
                            break;
                        default:
                            throw new AssertionError();
                    }
        return m;
    }
    public Autos getAutos(){
        return autoSeleccionado;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tabla_autos.getSelectedRow()>=0) {
            autoSeleccionado = controlAutos.getListaAuto().obtenerDato(tabla_autos.getSelectedRow());
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void cargarTabla(){
        controlAutos.getListaAuto();
        String[] columnas={"Chasis", "Marca", "Modelo", "Color", "Precio", "Año"};
        String[][] tabla = controlAutos.toArray();
        tabla_autos.removeAll();
        tabla_autos.setModel(new DefaultTableModel(tabla, columnas));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botn_salir;
    private javax.swing.JButton boton_editar;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox<String> combob_marca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNotifica;
    private javax.swing.JTable tabla_autos;
    private javax.swing.JTextField textf_anio;
    private javax.swing.JTextField textf_chasis;
    private javax.swing.JTextField textf_color;
    private javax.swing.JTextField textf_modelo;
    private javax.swing.JTextField textf_precio;
    // End of variables declaration//GEN-END:variables
}
